//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UDM.Insurance.Interface.RAMService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RAMService.TrackingWSSoap")]
    public interface TrackingWSSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld2(System.DateTime dt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Logon", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Logon(string userID, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserSessionValid", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool UserSessionValid(string userID, string logonToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsignmentDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode ConsignmentDetails(string userID, string logonToken, string consignmentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsignmentDetailsByShipperReference", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode ConsignmentDetailsByShipperReference(string userID, string logonToken, string shipperReference);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsignmentTracking", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode ConsignmentTracking(string userID, string logonToken, string consignmentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsignmentsTrackingStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode ConsignmentsTrackingStatus(string userID, string logonToken, string consignmentIDs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsignmentsTrackingStatusByShipperReferences", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode ConsignmentsTrackingStatusByShipperReferences(string userID, string logonToken, string shipperReferences);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsignmentTrackingByShipperReference", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode ConsignmentTrackingByShipperReference(string userID, string logonToken, string shipperReference);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PODImagesList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode PODImagesList(string userID, string logonToken, string consignmentID);
        
        // CODEGEN: Parameter 'PODImageByIndexResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PODImageByIndex", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        UDM.Insurance.Interface.RAMService.PODImageByIndexResponse PODImageByIndex(UDM.Insurance.Interface.RAMService.PODImageByIndexRequest request);
        
        // CODEGEN: Parameter 'MobileImageByIndexResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MobileImageByIndex", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        UDM.Insurance.Interface.RAMService.MobileImageByIndexResponse MobileImageByIndex(UDM.Insurance.Interface.RAMService.MobileImageByIndexRequest request);
        
        // CODEGEN: Parameter 'MobileImagesAsPDFResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MobileImagesAsPDF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        UDM.Insurance.Interface.RAMService.MobileImagesAsPDFResponse MobileImagesAsPDF(UDM.Insurance.Interface.RAMService.MobileImagesAsPDFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PODImages", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        byte[][] PODImages(string userID, string logonToken, string consignmentID);
        
        // CODEGEN: Parameter 'PODImageResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PODImage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        UDM.Insurance.Interface.RAMService.PODImageResponse PODImage(UDM.Insurance.Interface.RAMService.PODImageRequest request);
        
        // CODEGEN: Parameter 'PODImagesAsPDFResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PODImagesAsPDF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        UDM.Insurance.Interface.RAMService.PODImagesAsPDFResponse PODImagesAsPDF(UDM.Insurance.Interface.RAMService.PODImagesAsPDFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsignmentsConsignedByDay", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ConsignmentsConsignedByDay(string userID, string logonToken, System.DateTime day);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsignmentsDeliveredByDay", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ConsignmentsDeliveredByDay(string userID, string logonToken, System.DateTime day);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsignmentsNotDeliveredByDay", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ConsignmentsNotDeliveredByDay(string userID, string logonToken, System.DateTime day);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RAMShipperUndelivered", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet RAMShipperUndelivered(string userID, string logonToken, System.DateTime startDT, System.DateTime endDT);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RAMShipperDelivered", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet RAMShipperDelivered(string userID, string logonToken, System.DateTime startDT, System.DateTime endDT);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RAMShipperConsigned", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet RAMShipperConsigned(string userID, string logonToken, System.DateTime startDT, System.DateTime endDT);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetQuoteV2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetQuoteV2(
                    string userID, 
                    string logonToken, 
                    string billedTo, 
                    string serviceTypeCode, 
                    string sectorCode, 
                    string senderZoneID, 
                    string receiverZoneID, 
                    bool saturdaySurcharge, 
                    bool afterHoursSurcharge, 
                    bool insured, 
                    double insuredValue, 
                    bool armouredVehicle, 
                    double weight, 
                    double length, 
                    double breadth, 
                    double height);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetQuoteV3", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetQuoteV3(
                    string userID, 
                    string logonToken, 
                    string billedTo, 
                    string serviceTypeCode, 
                    string senderZoneID, 
                    string receiverZoneID, 
                    bool saturdaySurcharge, 
                    bool afterHoursSurcharge, 
                    bool insured, 
                    double insuredValue, 
                    bool armouredVehicle, 
                    bool faceToFaceSurcharge, 
                    double weight, 
                    double length, 
                    double breadth, 
                    double height, 
                    int noOfCards);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SuburbSearch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] SuburbSearch(string userID, string logonToken, string filter, int maxRecords);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SuburbsDownload", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] SuburbsDownload(string userID, string logonToken, int pageNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CacheView_Customers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet CacheView_Customers(string userID, string logonToken, string customerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CacheView_ConsignmentsArchive", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet CacheView_ConsignmentsArchive(string userID, string logonToken, string consignmentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CacheView_ParcelsArchive", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet CacheView_ParcelsArchive(string userID, string logonToken, string consignmentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LineHaulDepParcels", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet LineHaulDepParcels(string userID, string logonToken, string lineHaulDepID);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PODImageByIndex", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PODImageByIndexRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string logonToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string consignmentID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int imageIndex;
        
        public PODImageByIndexRequest() {
        }
        
        public PODImageByIndexRequest(string userID, string logonToken, string consignmentID, int imageIndex) {
            this.userID = userID;
            this.logonToken = logonToken;
            this.consignmentID = consignmentID;
            this.imageIndex = imageIndex;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PODImageByIndexResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PODImageByIndexResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] PODImageByIndexResult;
        
        public PODImageByIndexResponse() {
        }
        
        public PODImageByIndexResponse(byte[] PODImageByIndexResult) {
            this.PODImageByIndexResult = PODImageByIndexResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MobileImageByIndex", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class MobileImageByIndexRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string logonToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string reference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string recordType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string documentType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public int indexNo;
        
        public MobileImageByIndexRequest() {
        }
        
        public MobileImageByIndexRequest(string userID, string logonToken, string reference, string recordType, string documentType, int indexNo) {
            this.userID = userID;
            this.logonToken = logonToken;
            this.reference = reference;
            this.recordType = recordType;
            this.documentType = documentType;
            this.indexNo = indexNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MobileImageByIndexResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class MobileImageByIndexResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] MobileImageByIndexResult;
        
        public MobileImageByIndexResponse() {
        }
        
        public MobileImageByIndexResponse(byte[] MobileImageByIndexResult) {
            this.MobileImageByIndexResult = MobileImageByIndexResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MobileImagesAsPDF", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class MobileImagesAsPDFRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string logonToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string reference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string recordType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string documentType;
        
        public MobileImagesAsPDFRequest() {
        }
        
        public MobileImagesAsPDFRequest(string userID, string logonToken, string reference, string recordType, string documentType) {
            this.userID = userID;
            this.logonToken = logonToken;
            this.reference = reference;
            this.recordType = recordType;
            this.documentType = documentType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MobileImagesAsPDFResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class MobileImagesAsPDFResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] MobileImagesAsPDFResult;
        
        public MobileImagesAsPDFResponse() {
        }
        
        public MobileImagesAsPDFResponse(byte[] MobileImagesAsPDFResult) {
            this.MobileImagesAsPDFResult = MobileImagesAsPDFResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PODImage", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PODImageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string fragmentID;
        
        public PODImageRequest() {
        }
        
        public PODImageRequest(string fragmentID) {
            this.fragmentID = fragmentID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PODImageResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PODImageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] PODImageResult;
        
        public PODImageResponse() {
        }
        
        public PODImageResponse(byte[] PODImageResult) {
            this.PODImageResult = PODImageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PODImagesAsPDF", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PODImagesAsPDFRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string logonToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string consignmentID;
        
        public PODImagesAsPDFRequest() {
        }
        
        public PODImagesAsPDFRequest(string userID, string logonToken, string consignmentID) {
            this.userID = userID;
            this.logonToken = logonToken;
            this.consignmentID = consignmentID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PODImagesAsPDFResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PODImagesAsPDFResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] PODImagesAsPDFResult;
        
        public PODImagesAsPDFResponse() {
        }
        
        public PODImagesAsPDFResponse(byte[] PODImagesAsPDFResult) {
            this.PODImagesAsPDFResult = PODImagesAsPDFResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TrackingWSSoapChannel : UDM.Insurance.Interface.RAMService.TrackingWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TrackingWSSoapClient : System.ServiceModel.ClientBase<UDM.Insurance.Interface.RAMService.TrackingWSSoap>, UDM.Insurance.Interface.RAMService.TrackingWSSoap {
        
        public TrackingWSSoapClient() {
        }
        
        public TrackingWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TrackingWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TrackingWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TrackingWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public string HelloWorld2(System.DateTime dt) {
            return base.Channel.HelloWorld2(dt);
        }
        
        public string Logon(string userID, string password) {
            return base.Channel.Logon(userID, password);
        }
        
        public bool UserSessionValid(string userID, string logonToken) {
            return base.Channel.UserSessionValid(userID, logonToken);
        }
        
        public System.Xml.XmlNode ConsignmentDetails(string userID, string logonToken, string consignmentID) {
            return base.Channel.ConsignmentDetails(userID, logonToken, consignmentID);
        }
        
        public System.Xml.XmlNode ConsignmentDetailsByShipperReference(string userID, string logonToken, string shipperReference) {
            return base.Channel.ConsignmentDetailsByShipperReference(userID, logonToken, shipperReference);
        }
        
        public System.Xml.XmlNode ConsignmentTracking(string userID, string logonToken, string consignmentID) {
            return base.Channel.ConsignmentTracking(userID, logonToken, consignmentID);
        }
        
        public System.Xml.XmlNode ConsignmentsTrackingStatus(string userID, string logonToken, string consignmentIDs) {
            return base.Channel.ConsignmentsTrackingStatus(userID, logonToken, consignmentIDs);
        }
        
        public System.Xml.XmlNode ConsignmentsTrackingStatusByShipperReferences(string userID, string logonToken, string shipperReferences) {
            return base.Channel.ConsignmentsTrackingStatusByShipperReferences(userID, logonToken, shipperReferences);
        }
        
        public System.Xml.XmlNode ConsignmentTrackingByShipperReference(string userID, string logonToken, string shipperReference) {
            return base.Channel.ConsignmentTrackingByShipperReference(userID, logonToken, shipperReference);
        }
        
        public System.Xml.XmlNode PODImagesList(string userID, string logonToken, string consignmentID) {
            return base.Channel.PODImagesList(userID, logonToken, consignmentID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UDM.Insurance.Interface.RAMService.PODImageByIndexResponse UDM.Insurance.Interface.RAMService.TrackingWSSoap.PODImageByIndex(UDM.Insurance.Interface.RAMService.PODImageByIndexRequest request) {
            return base.Channel.PODImageByIndex(request);
        }
        
        public byte[] PODImageByIndex(string userID, string logonToken, string consignmentID, int imageIndex) {
            UDM.Insurance.Interface.RAMService.PODImageByIndexRequest inValue = new UDM.Insurance.Interface.RAMService.PODImageByIndexRequest();
            inValue.userID = userID;
            inValue.logonToken = logonToken;
            inValue.consignmentID = consignmentID;
            inValue.imageIndex = imageIndex;
            UDM.Insurance.Interface.RAMService.PODImageByIndexResponse retVal = ((UDM.Insurance.Interface.RAMService.TrackingWSSoap)(this)).PODImageByIndex(inValue);
            return retVal.PODImageByIndexResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UDM.Insurance.Interface.RAMService.MobileImageByIndexResponse UDM.Insurance.Interface.RAMService.TrackingWSSoap.MobileImageByIndex(UDM.Insurance.Interface.RAMService.MobileImageByIndexRequest request) {
            return base.Channel.MobileImageByIndex(request);
        }
        
        public byte[] MobileImageByIndex(string userID, string logonToken, string reference, string recordType, string documentType, int indexNo) {
            UDM.Insurance.Interface.RAMService.MobileImageByIndexRequest inValue = new UDM.Insurance.Interface.RAMService.MobileImageByIndexRequest();
            inValue.userID = userID;
            inValue.logonToken = logonToken;
            inValue.reference = reference;
            inValue.recordType = recordType;
            inValue.documentType = documentType;
            inValue.indexNo = indexNo;
            UDM.Insurance.Interface.RAMService.MobileImageByIndexResponse retVal = ((UDM.Insurance.Interface.RAMService.TrackingWSSoap)(this)).MobileImageByIndex(inValue);
            return retVal.MobileImageByIndexResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UDM.Insurance.Interface.RAMService.MobileImagesAsPDFResponse UDM.Insurance.Interface.RAMService.TrackingWSSoap.MobileImagesAsPDF(UDM.Insurance.Interface.RAMService.MobileImagesAsPDFRequest request) {
            return base.Channel.MobileImagesAsPDF(request);
        }
        
        public byte[] MobileImagesAsPDF(string userID, string logonToken, string reference, string recordType, string documentType) {
            UDM.Insurance.Interface.RAMService.MobileImagesAsPDFRequest inValue = new UDM.Insurance.Interface.RAMService.MobileImagesAsPDFRequest();
            inValue.userID = userID;
            inValue.logonToken = logonToken;
            inValue.reference = reference;
            inValue.recordType = recordType;
            inValue.documentType = documentType;
            UDM.Insurance.Interface.RAMService.MobileImagesAsPDFResponse retVal = ((UDM.Insurance.Interface.RAMService.TrackingWSSoap)(this)).MobileImagesAsPDF(inValue);
            return retVal.MobileImagesAsPDFResult;
        }
        
        public byte[][] PODImages(string userID, string logonToken, string consignmentID) {
            return base.Channel.PODImages(userID, logonToken, consignmentID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UDM.Insurance.Interface.RAMService.PODImageResponse UDM.Insurance.Interface.RAMService.TrackingWSSoap.PODImage(UDM.Insurance.Interface.RAMService.PODImageRequest request) {
            return base.Channel.PODImage(request);
        }
        
        public byte[] PODImage(string fragmentID) {
            UDM.Insurance.Interface.RAMService.PODImageRequest inValue = new UDM.Insurance.Interface.RAMService.PODImageRequest();
            inValue.fragmentID = fragmentID;
            UDM.Insurance.Interface.RAMService.PODImageResponse retVal = ((UDM.Insurance.Interface.RAMService.TrackingWSSoap)(this)).PODImage(inValue);
            return retVal.PODImageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UDM.Insurance.Interface.RAMService.PODImagesAsPDFResponse UDM.Insurance.Interface.RAMService.TrackingWSSoap.PODImagesAsPDF(UDM.Insurance.Interface.RAMService.PODImagesAsPDFRequest request) {
            return base.Channel.PODImagesAsPDF(request);
        }
        
        public byte[] PODImagesAsPDF(string userID, string logonToken, string consignmentID) {
            UDM.Insurance.Interface.RAMService.PODImagesAsPDFRequest inValue = new UDM.Insurance.Interface.RAMService.PODImagesAsPDFRequest();
            inValue.userID = userID;
            inValue.logonToken = logonToken;
            inValue.consignmentID = consignmentID;
            UDM.Insurance.Interface.RAMService.PODImagesAsPDFResponse retVal = ((UDM.Insurance.Interface.RAMService.TrackingWSSoap)(this)).PODImagesAsPDF(inValue);
            return retVal.PODImagesAsPDFResult;
        }
        
        public System.Data.DataSet ConsignmentsConsignedByDay(string userID, string logonToken, System.DateTime day) {
            return base.Channel.ConsignmentsConsignedByDay(userID, logonToken, day);
        }
        
        public System.Data.DataSet ConsignmentsDeliveredByDay(string userID, string logonToken, System.DateTime day) {
            return base.Channel.ConsignmentsDeliveredByDay(userID, logonToken, day);
        }
        
        public System.Data.DataSet ConsignmentsNotDeliveredByDay(string userID, string logonToken, System.DateTime day) {
            return base.Channel.ConsignmentsNotDeliveredByDay(userID, logonToken, day);
        }
        
        public System.Data.DataSet RAMShipperUndelivered(string userID, string logonToken, System.DateTime startDT, System.DateTime endDT) {
            return base.Channel.RAMShipperUndelivered(userID, logonToken, startDT, endDT);
        }
        
        public System.Data.DataSet RAMShipperDelivered(string userID, string logonToken, System.DateTime startDT, System.DateTime endDT) {
            return base.Channel.RAMShipperDelivered(userID, logonToken, startDT, endDT);
        }
        
        public System.Data.DataSet RAMShipperConsigned(string userID, string logonToken, System.DateTime startDT, System.DateTime endDT) {
            return base.Channel.RAMShipperConsigned(userID, logonToken, startDT, endDT);
        }
        
        public System.Data.DataSet GetQuoteV2(
                    string userID, 
                    string logonToken, 
                    string billedTo, 
                    string serviceTypeCode, 
                    string sectorCode, 
                    string senderZoneID, 
                    string receiverZoneID, 
                    bool saturdaySurcharge, 
                    bool afterHoursSurcharge, 
                    bool insured, 
                    double insuredValue, 
                    bool armouredVehicle, 
                    double weight, 
                    double length, 
                    double breadth, 
                    double height) {
            return base.Channel.GetQuoteV2(userID, logonToken, billedTo, serviceTypeCode, sectorCode, senderZoneID, receiverZoneID, saturdaySurcharge, afterHoursSurcharge, insured, insuredValue, armouredVehicle, weight, length, breadth, height);
        }
        
        public System.Data.DataSet GetQuoteV3(
                    string userID, 
                    string logonToken, 
                    string billedTo, 
                    string serviceTypeCode, 
                    string senderZoneID, 
                    string receiverZoneID, 
                    bool saturdaySurcharge, 
                    bool afterHoursSurcharge, 
                    bool insured, 
                    double insuredValue, 
                    bool armouredVehicle, 
                    bool faceToFaceSurcharge, 
                    double weight, 
                    double length, 
                    double breadth, 
                    double height, 
                    int noOfCards) {
            return base.Channel.GetQuoteV3(userID, logonToken, billedTo, serviceTypeCode, senderZoneID, receiverZoneID, saturdaySurcharge, afterHoursSurcharge, insured, insuredValue, armouredVehicle, faceToFaceSurcharge, weight, length, breadth, height, noOfCards);
        }
        
        public string[] SuburbSearch(string userID, string logonToken, string filter, int maxRecords) {
            return base.Channel.SuburbSearch(userID, logonToken, filter, maxRecords);
        }
        
        public string[] SuburbsDownload(string userID, string logonToken, int pageNo) {
            return base.Channel.SuburbsDownload(userID, logonToken, pageNo);
        }
        
        public System.Data.DataSet CacheView_Customers(string userID, string logonToken, string customerID) {
            return base.Channel.CacheView_Customers(userID, logonToken, customerID);
        }
        
        public System.Data.DataSet CacheView_ConsignmentsArchive(string userID, string logonToken, string consignmentID) {
            return base.Channel.CacheView_ConsignmentsArchive(userID, logonToken, consignmentID);
        }
        
        public System.Data.DataSet CacheView_ParcelsArchive(string userID, string logonToken, string consignmentID) {
            return base.Channel.CacheView_ParcelsArchive(userID, logonToken, consignmentID);
        }
        
        public System.Data.DataSet LineHaulDepParcels(string userID, string logonToken, string lineHaulDepID) {
            return base.Channel.LineHaulDepParcels(userID, logonToken, lineHaulDepID);
        }
    }
}
