//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UDM.Insurance.Interface.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTPhone
    {
        public long ID { get; set; }
        public string LoginName { get; set; }
        public string Password { get; set; }
        public string Extension { get; set; }
        public string Group { get; set; }
        public Nullable<long> StampUserID { get; set; }
        public Nullable<System.DateTime> StampDate { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
    }
}
