//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UDM.Insurance.Interface.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRStaffExtension
    {
        public long ID { get; set; }
        public Nullable<long> FKHRStaffID { get; set; }
        public Nullable<long> FKHRExtensionID { get; set; }
        public Nullable<long> FKRequesterHRStaffID { get; set; }
        public Nullable<System.DateTime> DateEffective { get; set; }
        public string Note { get; set; }
        public Nullable<long> StampUserID { get; set; }
        public Nullable<System.DateTime> StampDate { get; set; }
        public Nullable<long> ShiftType { get; set; }
        public Nullable<long> FKHRWorkstationID { get; set; }
        public Nullable<long> FKHRComputerID { get; set; }
    
        public virtual HRStaff HRStaff { get; set; }
        public virtual HRStaff HRStaff1 { get; set; }
        public virtual lkpHRExtension lkpHRExtension { get; set; }
    }
}
