//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UDM.Insurance.Interface.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRStaff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HRStaff()
        {
            this.HRStaffExtensions = new HashSet<HRStaffExtension>();
            this.HRStaffExtensions1 = new HashSet<HRStaffExtension>();
        }
    
        public long ID { get; set; }
        public string EmployeeNo { get; set; }
        public Nullable<System.DateTime> TempStartDate { get; set; }
        public Nullable<System.DateTime> EmploymentStartDate { get; set; }
        public Nullable<System.DateTime> EmploymentEndDate { get; set; }
        public Nullable<long> FKCompanyID { get; set; }
        public Nullable<long> FKStaffTypeID { get; set; }
        public Nullable<long> FKWorkStatusID { get; set; }
        public Nullable<long> FKJobTitleID { get; set; }
        public Nullable<long> FKUserID { get; set; }
        public Nullable<long> FKRecruitmentConsultantID { get; set; }
        public string RecruitmentSource { get; set; }
        public Nullable<long> FKTitleID { get; set; }
        public string Initials { get; set; }
        public string FirstName { get; set; }
        public string PreferredName { get; set; }
        public string Surname { get; set; }
        public Nullable<long> FKGenderID { get; set; }
        public Nullable<long> FKRaceID { get; set; }
        public string IDNo { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<long> FKCitizenID { get; set; }
        public Nullable<long> FKReligionID { get; set; }
        public string TelHome { get; set; }
        public string TelCell { get; set; }
        public string TelOther { get; set; }
        public string EMail { get; set; }
        public Nullable<bool> RegisteredTaxPayer { get; set; }
        public string TaxRefNo { get; set; }
        public string IRP5Number { get; set; }
        public Nullable<long> FKMedicalAidID { get; set; }
        public Nullable<bool> CriminalOffence { get; set; }
        public Nullable<bool> EmploymentDismissed { get; set; }
        public Nullable<bool> DisciplinaryGuilty { get; set; }
        public Nullable<bool> WorkedFinServicesIndustry { get; set; }
        public Nullable<System.DateTime> WorkedFinServicesIndustryFrom { get; set; }
        public Nullable<System.DateTime> WorkedFinServicesIndustryTo { get; set; }
        public Nullable<System.DateTime> RegLevel1ExamDate { get; set; }
        public string Note { get; set; }
        public Nullable<long> FKAutomationStatusID { get; set; }
        public Nullable<System.DateTime> AutomationDate { get; set; }
        public Nullable<long> StampUserID { get; set; }
        public Nullable<System.DateTime> StampDate { get; set; }
        public string PassportNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRStaffExtension> HRStaffExtensions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRStaffExtension> HRStaffExtensions1 { get; set; }
    }
}
