//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UDM.Insurance.Interface.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lkpHRExtension
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public lkpHRExtension()
        {
            this.HRStaffExtensions = new HashSet<HRStaffExtension>();
        }
    
        public long ID { get; set; }
        public string Extension { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> StampDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRStaffExtension> HRStaffExtensions { get; set; }
    }
}
