//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UDM.Insurance.Interface.MercantileService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="cdvResponse", Namespace="http://schemas.datacontract.org/2004/07/mpscdv")]
    [System.SerializableAttribute()]
    public partial class cdvResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cdvResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cdvResult {
            get {
                return this.cdvResultField;
            }
            set {
                if ((object.ReferenceEquals(this.cdvResultField, value) != true)) {
                    this.cdvResultField = value;
                    this.RaisePropertyChanged("cdvResult");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MercantileService.ICdvWCF")]
    public interface ICdvWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICdvWCF/checkCDV", ReplyAction="http://tempuri.org/ICdvWCF/checkCDVResponse")]
        UDM.Insurance.Interface.MercantileService.cdvResponse checkCDV(string username, string userinst, string password, string branch, string account);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICdvWCFChannel : UDM.Insurance.Interface.MercantileService.ICdvWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CdvWCFClient : System.ServiceModel.ClientBase<UDM.Insurance.Interface.MercantileService.ICdvWCF>, UDM.Insurance.Interface.MercantileService.ICdvWCF {
        
        public CdvWCFClient() {
        }
        
        public CdvWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CdvWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CdvWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CdvWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public UDM.Insurance.Interface.MercantileService.cdvResponse checkCDV(string username, string userinst, string password, string branch, string account) {
            return base.Channel.checkCDV(username, userinst, password, branch, account);
        }
    }
}
